gantsign/ansible-role-maven

- .gitignore
- .travis.yml
- README.md
- ansible.cfg
- molecule.yml
- tests/inventory
- tests/test.yml
- tests/test_role.py
Makes it easy to test locally during development.
Enhancement: resolves #1
> Switched to use Molecule to test role

- README.md
It makes more sense to document version before home.
> Reordered Ansible fact documentation

- README.md
> Corrected Ansible fact names in documentation

- README.md
- vars/versions/3.1.1.yml
- vars/versions/3.2.5.yml
Useful for those still on Java 6/5.
Enhancement: resolves #20
Enhancement: resolves #21
> Add support for older Maven versions

- README.md
Needed to cover Java requirements specifically, but expanded on other requirements as well.
> Expanded requirements in README.md

- README.md
Help users add color to their Maven life.
> Added related roles to README.md

- README.md
- vars/versions/3.1.1.yml
- vars/versions/3.2.5.yml
- vars/versions/3.3.9.yml
> Quoted sha256 sum

- README.md
Fixed line wrapping in the related roles section of the README.md.
> Fixed line wrapping in related roles

- .travis.yml
- tests/test_role.py
> Upgraded to Molecule 1.10.3

- molecule.yml
- tests/test.yml
Include Ubuntu 14.04 in test matrix.
> Test Ubuntu 14.04

- README.md
- meta/main.yml
- molecule.yml
- tests/test.yml
* Include Debian 7 & 8 to test matrix.
* Add to Ansible metadata.
Enhancement: resolves #40
> Add support for Debian 7 & 8

- README.md
- meta/main.yml
- molecule.yml
- tasks/main.yml
- tests/test.yml
* Added to test matrix
* Added to ansible metadata
* Added missing dependency
Enhancement: resolves #41
> Added support for CentOS 6 & 7

- .travis.yml
Keeping up with the latest changes.
> Upgraded to Molecule 1.11.1

- README.md
- meta/main.yml
- molecule.yml
- tasks/main.yml
- tests/test.yml
- Added to test matrix
- Added to Ansible metadata
- Added dnf package support
Enhancement: resolves #43
> Added support for Fedora 25

- README.md
- meta/main.yml
- molecule.yml
- tasks/main.yml
- tests/test.yml
- Added to test matrix
- Added Ansble metadata
- Install dependencies with zypper
Enhancement: resolves #46
> Added support for OpenSUSE 42.2

- README.md
I expect it is relatively common to need to specify the version explicitly.
> Added example playbook with explicit version

- tests/test.yml
To ensure facts have been defined.
> Added check to verify Maven facts

- tests/test_role.py
Looks like name was copied from another role and was a little inaccurate for this role.
> Fixed test case name

- tests/test_role.py
Check the path, file ownership and permissions.
> Added test for path and attributes of executables

- tests/test_role.py
Check the fact file is written and has the appropriate owner and permissions.
> Added test for Ansible fact file

- README.md
- defaults/main.yml
- tasks/create-symbolic-links.yml
- tasks/main.yml
Useful for installing multiple Maven versions at once.
> Added option to disable linking executables

- README.md
- meta/main.yml
- molecule/debian-max/molecule.yml
- molecule/debian-max/playbook.yml
Ensure this role works with Debian Stretch.
> Increased upper Debian test range to Stretch

- README.md
- meta/main.yml
- molecule/fedora/molecule.yml
> Increased supported Fedora version to 27

- README.md
- molecule/opensuse/molecule.yml
> Increased supported openSUSE version to 42.3

- templates/facts.j2
Allow for a more verbose ansible_managed message.
> Added support for multiline ansible_managed

- README.md
- defaults/main.yml
- molecule/centos-max/playbook.yml
- molecule/centos-min/playbook.yml
- molecule/debian-max/playbook.yml
- molecule/debian-min/playbook.yml
- molecule/default/playbook.yml
- molecule/default/tests/test_role.py
- molecule/fedora/playbook.yml
- molecule/opensuse/playbook.yml
- molecule/single/tests/test_role.py
- molecule/ubuntu-min/playbook.yml
- vars/versions/3.5.2.yml
`3.5.2` is now the default version installed.
> Updated to Maven to version 3.5.2

- README.md
- defaults/main.yml
- molecule/centos-max/playbook.yml
- molecule/centos-min/playbook.yml
- molecule/debian-max/playbook.yml
- molecule/debian-min/playbook.yml
- molecule/default/playbook.yml
- molecule/default/tests/test_role.py
- molecule/fedora/playbook.yml
- molecule/opensuse/playbook.yml
- molecule/single/tests/test_role.py
- molecule/ubuntu-min/playbook.yml
- vars/versions/3.5.3.yml
`3.5.3` is now the default version installed.
> Updated to Maven to version 3.5.3

- README.md
- defaults/main.yml
- molecule/centos-max/playbook.yml
- molecule/centos-min/playbook.yml
- molecule/debian-max/playbook.yml
- molecule/debian-min/playbook.yml
- molecule/default/playbook.yml
- molecule/default/tests/test_role.py
- molecule/fedora/playbook.yml
- molecule/opensuse/playbook.yml
- molecule/single/tests/test_role.py
- molecule/ubuntu-min/playbook.yml
- vars/versions/3.5.4.yml
`3.5.4` is now the default version installed.
> Updated to Maven to version 3.5.4

- molecule/centos-max/molecule.yml
- molecule/centos-min/molecule.yml
- molecule/debian-max/molecule.yml
- molecule/debian-min/molecule.yml
- molecule/fedora/molecule.yml
- molecule/opensuse/molecule.yml
- molecule/ubuntu-min/molecule.yml
Removed unnecessary trailing slash.
> Fixed location of Molecule tests

- molecule/centos-max/molecule.yml
- molecule/centos-min/molecule.yml
- molecule/debian-max/molecule.yml
- molecule/debian-min/molecule.yml
- molecule/default/molecule.yml
- molecule/opensuse/molecule.yml
- molecule/ubuntu-min/molecule.yml
To make the platforms easier to update.
> Made Molecule platform names more generic

- README.md
- defaults/main.yml
- molecule/centos-max/playbook.yml
- molecule/centos-min/playbook.yml
- molecule/debian-max/playbook.yml
- molecule/debian-min/playbook.yml
- molecule/default/playbook.yml
- molecule/default/tests/test_role.py
- molecule/fedora/playbook.yml
- molecule/opensuse/playbook.yml
- molecule/single/tests/test_role.py
- molecule/ubuntu-min/playbook.yml
- vars/versions/3.6.0.yml
`3.6.0` is now the default version installed.
> Updated to Maven to version 3.6.0

- README.md
- defaults/main.yml
- molecule/centos-max/playbook.yml
- molecule/centos-min/playbook.yml
- molecule/debian-max/playbook.yml
- molecule/debian-min/playbook.yml
- molecule/default/playbook.yml
- molecule/default/tests/test_role.py
- molecule/fedora/playbook.yml
- molecule/opensuse/playbook.yml
- molecule/single/tests/test_role.py
- molecule/ubuntu-min/playbook.yml
- vars/versions/3.6.1.yml
`3.6.1` is now the default version installed.
> Updated to Maven to version 3.6.1

- README.md
- defaults/main.yml
- tasks/main.yml
For users on slow internet connections.
Enhancement: resolves #116
> Made download timeout configurable

- README.md
- defaults/main.yml
- molecule/centos-max/playbook.yml
- molecule/centos-min/playbook.yml
- molecule/debian-max/playbook.yml
- molecule/debian-min/playbook.yml
- molecule/default/playbook.yml
- molecule/default/tests/test_role.py
- molecule/fedora/playbook.yml
- molecule/opensuse/playbook.yml
- molecule/single/tests/test_role.py
- molecule/ubuntu-min/playbook.yml
- vars/versions/3.6.2.yml
`3.6.2` is now the default version installed.
> Updated to Maven to version 3.6.2

- README.md
- meta/main.yml
- molecule/fedora/molecule.yml
- molecule/fedora/playbook.yml
> Upgraded Fedora version to 31

- README.md
- defaults/main.yml
- molecule/centos-max/playbook.yml
- molecule/centos-min/playbook.yml
- molecule/debian-max/playbook.yml
- molecule/debian-min/playbook.yml
- molecule/default/playbook.yml
- molecule/default/tests/test_role.py
- molecule/fedora/playbook.yml
- molecule/opensuse/playbook.yml
- molecule/single/tests/test_role.py
- molecule/ubuntu-min/playbook.yml
- vars/versions/3.6.3.yml
`3.6.3` is now the default version installed.
> Updated to Maven to version 3.6.3

- tasks/create-symbolic-links.yml
- tasks/main.yml
The group name varies by OS (e.g. root/wheel)
Enhancment: resolves #133
> Changed to use group ID 0 rather than group name

- .github/workflows/ci.yml
To workaround the download limits.
> Changed workflow to login to Docker Hub

- README.md
- meta/main.yml
- molecule/centos-max/molecule.yml
> Increased upper CentOS test version to 8

- README.md
- defaults/main.yml
- vars/versions/3.8.1.yml
`3.8.1` is now the default version installed.
> Updated to Maven to version 3.8.1

- README.md
- defaults/main.yml
- tasks/main.yml
For corporate proxies/firewalls.
> Added variables for use_proxy and validate_certs

- README.md
- defaults/main.yml
- vars/versions/3.8.2.yml
`3.8.2` is now the default version installed.
> Updated to Maven to version 3.8.2

- README.md
- meta/main.yml
- molecule/debian-max/converge.yml
- molecule/debian-max/molecule.yml
Bullseye is the latest stable version of Debian.
> Increased upper Debian test version to Bullseye

- molecule/centos-max/converge.yml
- molecule/centos-min/converge.yml
- molecule/debian-max/converge.yml
- molecule/debian-min/converge.yml
- molecule/default/converge.yml
- molecule/default/tests/test_role.py
- molecule/fedora/converge.yml
- molecule/opensuse/converge.yml
- molecule/single/tests/test_role.py
- molecule/ubuntu-min/converge.yml
Previous version was hard coded.
> Fixed Maven 3.8.2 tests

- molecule/debian-max/molecule.yml
- molecule/debian-min/molecule.yml
- molecule/fedora/molecule.yml
- molecule/opensuse/molecule.yml
- molecule/rocky/molecule.yml
- molecule/ubuntu-min/molecule.yml
Molecule no longer requires a Dockerfile.
> Removed unused Dockerfile config

- README.md
- meta/main.yml
- molecule/fedora/molecule.yml
> Upgraded Fedora version to 34

- README.md
- meta/main.yml
- molecule/opensuse/molecule.yml
> Upgraded openSUSE version to 15.2

- README.md
Focal was previously removed by mistake.
> Fixed supported Ubuntu versions in README.md

- README.md
- defaults/main.yml
- molecule/debian-max/converge.yml
- molecule/debian-min/converge.yml
- molecule/default/converge.yml
- molecule/default/tests/test_role.py
- molecule/fedora/converge.yml
- molecule/opensuse/converge.yml
- molecule/rocky/converge.yml
- molecule/single/tests/test_role.py
- molecule/ubuntu-min/converge.yml
- vars/versions/3.8.4.yml
`3.8.4` is now the default version installed.
> Updated to Maven to version 3.8.4

- README.md
- defaults/main.yml
- molecule/debian-max/converge.yml
- molecule/debian-min/converge.yml
- molecule/default/converge.yml
- molecule/default/tests/test_role.py
- molecule/fedora/converge.yml
- molecule/opensuse/converge.yml
- molecule/rocky/converge.yml
- molecule/single/tests/test_role.py
- molecule/ubuntu-min/converge.yml
- vars/versions/3.8.5.yml
`3.8.5` is now the default version installed.
> Updated to Maven to version 3.8.5

- README.md
- defaults/main.yml
- molecule/debian-max/converge.yml
- molecule/debian-min/converge.yml
- molecule/default/converge.yml
- molecule/default/tests/test_role.py
- molecule/fedora/converge.yml
- molecule/opensuse/converge.yml
- molecule/rocky/converge.yml
- molecule/single/tests/test_role.py
- molecule/ubuntu-min/converge.yml
- vars/versions/3.8.6.yml
`3.8.6` is now the default version installed.
> Updated to Maven to version 3.8.6

- README.md
- defaults/main.yml
- molecule/debian-max/converge.yml
- molecule/debian-min/converge.yml
- molecule/default/converge.yml
- molecule/default/tests/test_role.py
- molecule/fedora/converge.yml
- molecule/opensuse/converge.yml
- molecule/rocky/converge.yml
- molecule/single/tests/test_role.py
- molecule/ubuntu-min/converge.yml
- vars/versions/3.8.7.yml
`3.8.7` is now the default version installed.
> Updated to Maven to version 3.8.7

- README.md
- defaults/main.yml
- molecule/debian-max/converge.yml
- molecule/debian-min/converge.yml
- molecule/default/converge.yml
- molecule/default/tests/test_role.py
- molecule/fedora/converge.yml
- molecule/opensuse/converge.yml
- molecule/rocky/converge.yml
- molecule/single/tests/test_role.py
- molecule/ubuntu-min/converge.yml
- vars/versions/3.8.8.yml
`3.8.8` is now the default version installed.
> Updated to Maven to version 3.8.8

- README.md
- defaults/main.yml
- molecule/debian-max/converge.yml
- molecule/debian-min/converge.yml
- molecule/default/converge.yml
- molecule/default/tests/test_role.py
- molecule/fedora/converge.yml
- molecule/opensuse/converge.yml
- molecule/rocky/converge.yml
- molecule/single/tests/test_role.py
- molecule/ubuntu-min/converge.yml
- vars/versions/3.9.0.yml
`3.9.0` is now the default version installed.
> Updated to Maven to version 3.9.0

- README.md
- defaults/main.yml
- molecule/debian-max/converge.yml
- molecule/debian-min/converge.yml
- molecule/default/converge.yml
- molecule/default/tests/test_role.py
- molecule/fedora/converge.yml
- molecule/opensuse/converge.yml
- molecule/rocky/converge.yml
- molecule/single/tests/test_role.py
- molecule/ubuntu-min/converge.yml
- vars/versions/3.9.1.yml
`3.9.1` is now the default version installed.
> Updated to Maven to version 3.9.1

- README.md
- defaults/main.yml
- meta/main.yml
- molecule/debian-max/converge.yml
- molecule/debian-max/molecule.yml
- molecule/debian-min/converge.yml
- molecule/debian-min/molecule.yml
- molecule/default/converge.yml
- molecule/default/molecule.yml
- molecule/fedora/converge.yml
- molecule/fedora/molecule.yml
- molecule/opensuse/converge.yml
- molecule/opensuse/molecule.yml
- molecule/rocky/converge.yml
- molecule/rocky/molecule.yml
- molecule/ubuntu-min/converge.yml
- molecule/ubuntu-min/molecule.yml
- tasks/create-symbolic-links.yml
- tasks/main.yml
In preparation for Molecule upgrade.
> Fixed Ansible Lint warnings

- defaults/main.yml
- molecule/debian-max/converge.yml
- molecule/debian-min/converge.yml
- molecule/default/converge.yml
- molecule/fedora/converge.yml
- molecule/opensuse/converge.yml
- molecule/rocky/converge.yml
- molecule/ubuntu-min/converge.yml
- tasks/create-symbolic-links.yml
- tasks/main.yml
- vars/main.yml
For improved VS Code editing support.
> Added Ansible modelines

- README.md
- defaults/main.yml
- molecule/debian-max/converge.yml
- molecule/debian-min/converge.yml
- molecule/default/converge.yml
- molecule/default/tests/test_role.py
- molecule/fedora/converge.yml
- molecule/opensuse/converge.yml
- molecule/rocky/converge.yml
- molecule/single/tests/test_role.py
- molecule/ubuntu-min/converge.yml
- vars/versions/3.9.2.yml
`3.9.2` is now the default version installed.
> Updated to Maven to version 3.9.2

- README.md
- defaults/main.yml
- molecule/debian-max/converge.yml
- molecule/debian-min/converge.yml
- molecule/default/converge.yml
- molecule/default/tests/test_role.py
- molecule/fedora/converge.yml
- molecule/opensuse/converge.yml
- molecule/rocky/converge.yml
- molecule/single/tests/test_role.py
- molecule/ubuntu-min/converge.yml
- vars/versions/3.9.3.yml
`3.9.3` is now the default version installed.
> Updated to Maven to version 3.9.3

- .devcontainer/devcontainer.json
Saves a lot of time building it.
> Changed to use GantSign devcontainer image

- README.md
- defaults/main.yml
- molecule/debian-max/converge.yml
- molecule/debian-min/converge.yml
- molecule/default/converge.yml
- molecule/default/tests/test_role.py
- molecule/fedora/converge.yml
- molecule/opensuse/converge.yml
- molecule/rocky/converge.yml
- molecule/single/tests/test_role.py
- molecule/ubuntu-min/converge.yml
- vars/versions/3.9.4.yml
`3.9.4` is now the default version installed.
> Updated to Maven to version 3.9.4

- .devcontainer/devcontainer.json
> Fixed dev container name

- .github/dependabot.yml
In preparation for upgrade to Ansible Lint 24.10.0.
> Fixed lint error

- .github/workflows/ci.yml
- README.md
- meta/main.yml
- molecule/default/molecule.yml
The old LTS release of Ubuntu.
> Increased upper Ubuntu test version to Jammy

- requirements/ansible-max.in
- requirements/ansible-max.txt
- requirements/ansible-min.txt
- requirements/dev.txt
Ensure this role works with Ansible Core 2.17.6.
> Increased upper Ansible Core test range to 2.17.6

- .github/workflows/ci.yml
- README.md
- meta/main.yml
- molecule/default/molecule.yml
The latest LTS release of Ubuntu.
> Increased upper Ubuntu test version to Noble

- README.md
- meta/main.yml
- molecule/debian-max/converge.yml
- molecule/debian-max/molecule.yml
Bookworm is the latest stable version of Debian.
> Increased upper Debian test version to Bookworm
