gantsign/ansible-role-maven

- README.md
- defaults/main.yml
Changed default for `maven_download_dir` from `/tmp/ansible/data` to `~/.ansible/tmp/downloads`.
Enhancement: resolves #6
> Moved default maven_download_dir under user home

- README.md
- templates/facts.j2
Was unnecessarily verbose.
Enhancement: resolves #11
> Removed "maven_" prefix from Maven facts

- templates/facts.j2
This is useful to tell users that a file has been placed by Ansible and manual changes are likely to be overwritten.
> Added ansible_managed header to template file

- tasks/main.yml
- tests/test.yml
Now using `ansible_pkg_mgr` instead of `ansible_os_family` to decide whether to use yum.
> Improved handling for YUM

- meta/main.yml
CentOS is included in the EL platform in Ansible Galaxy.
> Fixed CentOS metadata

- README.md
- defaults/main.yml
Ensure the `maven_download_dir` defaults to the remote users home directory rather than the local user.
> Fixed default maven_download_dir home

- tasks/main.yml
- vars/main.yml
Switched to single quotes (rather than double quotes) for YAML strings where escaping isn't required.
> Switched to single quotes for YAML strings

- meta/main.yml
Ansible Galaxy doesn't support version 42.2 yet.
> Temporally disable OpenSUSE metadata

- README.md
- defaults/main.yml
- tasks/main.yml
- tests/test.yml
- tests/test_role.py
To avoid overwriting the fact file and give you access to the facts for multiple Maven versions.
> Added fact group name for multiple version support

- README.md
- defaults/main.yml
- tests/test.yml
- tests/test_role.py
- vars/versions/3.5.0.yml
3.5.0 will now be installed by default.
> Updated Maven to 3.5.0

- molecule/default/tests/test_role.py
- molecule/single/tests/test_role.py
Other fixtures are deprecated and will be removed in 2.0 Testinfra release.
> Changed tests to use host fixture

- README.md
> Documented minimum JDK version for Maven 3.6.0

- README.md
Due to the move to AdoptOpenJDK.
> Updated documentation on gantsign.java role

- README.md
The `gantsign.maven-color` role is deprecated.
> Dropped reference to gantsign.maven-color role

- README.md
- meta/main.yml
- molecule/ubuntu-min/molecule.yml
- molecule/ubuntu-min/playbook.yml
Canonical have ended standard support for Ubuntu Trusty (14.04).
> Dropped support for Ubuntu Trusty

- tasks/main.yml
In order to fix
```
[DEPRECATION WARNING]: The parameter "sha256sum" has been deprecated and will 
be removed, use "checksum" instead. This feature will be removed from ansible-
base in version 2.14. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
```
> Replace deprecated sha256sum to checksum

- README.md
- meta/main.yml
- molecule/centos-min/molecule.yml
Maintenance updates for CentOS 6 ended on 2020-11-30.
> Dropped support for CentOS 6

- defaults/main.yml
- tasks/main.yml
Allow to override use_proxy and validate_certs
I need to disable proxy and certificats check
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gantsign/ansible-role-maven/148)
> Allow to override use_proxy and validate_certs

- README.md
- meta/main.yml
- molecule/debian-min/converge.yml
- molecule/debian-min/molecule.yml
Debian ended LTS support in June 2020.
> Dropped support for Debian Jessie

- README.md
- meta/main.yml
- molecule/debian-min/molecule.yml
Debian standard support ended on 01 Jul 2022.
> Dropped support for Debian Stretch

- README.md
- meta/main.yml
- molecule/opensuse/molecule.yml
Leap defaults to Python 3.6, which is too old for recent Ansible versions.
> Changed openSUSE tests to use Tumbleweed

- README.md
- meta/main.yml
- molecule/ubuntu-min/molecule.yml
Canonical have ended standard support for Ubuntu Focal.
> Dropped support for Ubuntu Focal

- README.md
- meta/main.yml
- molecule/debian-min/molecule.yml
Debian standard support ended on 30 Jun 2025.
> Dropped support for Debian Buster
